name: Deploy Bot to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git pull origin main
            docker compose up -d --build